### ISSUE TITLE
App is crashing - resource not found exception 

### ISSUE THREAD

**Issue by rj686** [professorDeveloper/Easy-Quiz-App#1]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.azamovhudstc.quizapp/com.azamovhudstc.quizapp.ui.SplashScreen}: android.content.res.Resources$NotFoundException: Resource ID #0x7f080112

**Comment by professorDeveloper** [comment]
I fixed it, you can try reinstalling or update via git

**Comment by professorDeveloper** [comment]
Bug Fixed  👍 )

**Comment by rj686** [comment]
> Bug Fixed 👍 )

Pls update app-release.aab. people may want to test the app without building it

**Comment by professorDeveloper** [comment]
> > Bug Fixed 👍 )
> 
> Pls update app-release.aab. people may want to test the app without building it

okay bro

**Comment by professorDeveloper** [comment]
I **updated the abb**, you can update the code again
